# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_goods2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods2',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
